# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:

  - stage: WorkflowAnalyser
    displayName: RunWorkflow Analyser
    dependsOn: Build
    condition: succeeded()
    jobs:
        - job: WorkflowAnalyser
          displayName: AnalyseProject Using Workflow Cli
          pool: MyAubay
          steps:
          - task: PowerShell@2
            inputs:
              targetType: filePath
              filePath: $(Build.SourcesDirectory)\Data\Workflow-Analyzer-CLI-Script
              arguments: > # Use this to avoid newline characters in multiline string
                -ProjectFilePath $(Build.SourcesDirectory)\project.json
                -ExecutableFilePath "C:\Users\skonate\AppData\Local\Programs\UiPath\Studio\UiPath.Studio.CommandLine.exe"
                -OutputFilePath '$(Pipeline.Workspace)\drop\Workflow-Analysis.json'
              workingDirectory: $(Build.SourcesDirectory)
            displayName: 'Analyse Project'
